---
# ==============================================================================
# Filename:       roles/system_mail_client/tasks/main.yml
# Version:        1.1
# Author:         Gemini CLI
# Last Modified:  2026-02-05
# Context:        http://trac.home.arpa/ticket/3036
#
# Purpose:
#     Tasks for configuring Postfix as a null-client satellite relay.
# ==============================================================================
- name: Install Postfix (satellite mode)
  apt:
    name:
      - postfix
      - mailutils
    state: present
    update_cache: yes

- name: Configure Postfix as Null Client
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'
  notify: restart postfix

- name: Configure root alias
  lineinfile:
    path: /etc/aliases
    regexp: '^root:'
    line: "root: {{ system_mail_root_alias }}"
  notify: update aliases

- name: Ensure Postfix is started and enabled
  service:
    name: postfix
    state: started
    enabled: yes

- name: Flush handlers to apply configuration
  meta: flush_handlers
