---
- name: Configure DHCP client
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Enable Pi-hole DHCP with range 10.0.6.50-10.0.6.100
      sbarbett.pihole.dhcp_config:
        url: "https://your-pihole.example.com"
        password: "{{ pihole_password }}"
        state: present
        start: "10.0.7.50"
        end: "10.0.7.100"
        router: "10.0.7.1"
        # (Optional) Leave netmask undefined to infer it from the device.
        # netmask: "255.255.255.0"
        # (Optional) The default lease time, if left unspecified, is 1 hour for IPv4 and 1 day for IPv6.
        lease_time: "7d"
        # (Optional) IPv6 is false by default and only used if the Pi-hole supports it.
        # ipv6: true
        # (Optional) Enables DHCPv4 rapid commit (faster address assignment).
        # rapid_commit: true
        # (Optional) Advertise Pi-hole DNS multiple times to mitigate clients adding their own DNS servers.
        # multi_dns: true
        # (Optional)When True, Pi-hole DHCP grants addresses only to clients specifically defined in dhcp.hosts (static reservations).
        # ignore_end: true
