# playbook: standard_debian_desktop_software_config.yml
# description: This playbook installs standard desktop software (e.g., VLC, Screen) on Debian-based desktop hosts.
# prerequisites: Hosts must be part of the 'desktops' Ansible group.
# when_run: Run this playbook when setting up new Debian desktop machines or updating standard software.
# version: 1.0.0
---
- name: Standard Debian Desktop Software Configuration
  hosts: desktops
  become: true
  tasks:
    - name: Install vlc package
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - vlc
          - screen
