# ------------------------------------------------------------------------------
# Playbook: standard_debian_desktop_software_config.yml
# Path: /opt/netbox/ansible-netbox/playbooks/standard_debian_desktop_software_config.yml
# Trac Ticket: #2888
# Wiki Page: http://192.168.0.99/mediawiki/index.php/Playbooks/standard_debian_desktop_software_config.yml
#
# Purpose:
#   This playbook installs standard desktop software (e.g., VLC, Screen, 
#   python3.11-venv) on Debian-based desktop hosts.
#
# Prerequisites:
#   - Hosts must be part of the 'desktops' Ansible group.
#
# Usage:
#   ansible-playbook -i inventory.ini playbooks/standard_debian_desktop_software_config.yml
# ------------------------------------------------------------------------------
---
- name: Standard Debian Desktop Software Configuration
  hosts: desktops
  become: true
  tasks:
    - name: Install standard desktop packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - vlc
          - screen
          - python3.11-venv